# Exported from Render on 2025-07-30T18:37:50Z
services:
- type: web
  name: YouTubeTool-frontend
  runtime: static
  repo: https://github.com/aarif-123/YouTubeTool
  envVars:
  - key: VITE_SUPABASE_ANON_KEY
    sync: false
  - key: VITE_SUPABASE_URL
    sync: false
  - key: VITE_BACKEND_URL
    sync: false
  buildCommand: npm install && npm run build
  staticPublishPath: dist
  autoDeployTrigger: commit
version: "1"
