services:
  # Backend API service
  - type: web
    name: yt-snap-to-pdf-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: frames
      mountPath: /opt/render/project/src/frames
      sizeGB: 1

  # Frontend web service
  - type: web
    name: yt-snap-to-pdf-web
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: VITE_API_URL
        value: https://yt-snap-to-pdf-api.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
